<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Search products_fa fa-user collapsed</name>
   <tag></tag>
   <elementGuidId>3abeba06-d73b-4142-8abb-755cc789a643</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-user.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header/div/nav/div/div/div[3]/div/ul/div/ul/li[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>aae865af-915c-4edb-a486-53230d9da821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f8635f0d-b323-494e-a1c8-d7255c7f1659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>61a2caea-6a3c-47c5-a948-e2ae1ea3dd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>88c0ac21-44e6-4a66-b87e-bf7ec2250583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sidebar-cart</value>
      <webElementGuid>d6e67568-1948-4a6a-85c2-31618026660a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-user collapsed</value>
      <webElementGuid>39af0270-9784-4930-8d96-207eae796db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Login/Signup</value>
      <webElementGuid>4676af20-7a0f-4bd7-9308-e721325437ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>__bv_tooltip_9__</value>
      <webElementGuid>9455bcd9-1618-4cf2-8500-12f51659c315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[@class=&quot;header&quot;]/div[@class=&quot;bottom-header&quot;]/nav[@class=&quot;navbar navbar-expand-lg&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row w-100 d-flex justify-content-between&quot;]/div[@class=&quot;bottom-header-area col-4  col-lg-4 pl-0 pl-xl-5 justify-content-end&quot;]/div[@class=&quot;heart-icon&quot;]/ul[@class=&quot;m-0 p-0 pl-0&quot;]/div[@class=&quot;d-inline-flex header-buttons&quot;]/ul[@class=&quot;mb-0  d-inline-flex sidebar-cart-items p-0&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;main-cart-icon hover-effect&quot;]/i[@class=&quot;fa fa-user collapsed&quot;]</value>
      <webElementGuid>b4084d15-9ab1-4001-bfe0-7bfff4fbd0af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header/div/nav/div/div/div[3]/div/ul/div/ul/li[2]/a/i</value>
      <webElementGuid>6581eb9e-6dc7-4d33-aab9-2b89a8180a2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/i</value>
      <webElementGuid>4a1dcb32-1872-4f6b-99df-cad5b2edfc3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
