<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__a-8ktridki9qh2</name>
   <tag></tag>
   <elementGuidId>cc680ad2-1dba-4668-9980-207a285cf1b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-8ktridki9qh2&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-8ktridki9qh2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-8ktridki9qh2&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>beef86b7-478c-4e1c-b1c3-1b57804156d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>60c06668-f58a-4020-a1e8-df86bce20fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>ff309321-4f64-4617-acca-1ff0c166af11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>1268f2c3-b03f-438e-8551-b67e385604b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>6e2d8955-e9ac-46f7-ab45-8933c1af619b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-8ktridki9qh2</value>
      <webElementGuid>d05c9616-6a03-4048-8317-f31310c2ce27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3c721569-5f9b-4d93-9df4-6b4c4563f2a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>1d7cdb37-fbd3-437e-9657-1b2b66d2514d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>8db78436-f0bb-47d3-a1ce-d0ad466238fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_&amp;co=aHR0cHM6Ly9zdGFnaW5nLnJhcmFtYXJrZXQuanA6NDQz&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;theme=light&amp;size=normal&amp;cb=htl08h3wtmsp</value>
      <webElementGuid>2fb909b1-edf9-462c-a3ec-44631003766f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-response-value-b3ada1048960467083103f8b90dd0ce6&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>fc118596-f1ce-466c-96e9-d51cc525a4b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-8ktridki9qh2']</value>
      <webElementGuid>74868a04-6194-4e75-bb85-08bcf740d91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-response-value-b3ada1048960467083103f8b90dd0ce6']/div/div/iframe</value>
      <webElementGuid>de849de7-7946-4654-b47e-e47a996cd857</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>7727c5e4-1f6f-455a-a279-68cb804ec5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-8ktridki9qh2' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_&amp;co=aHR0cHM6Ly9zdGFnaW5nLnJhcmFtYXJrZXQuanA6NDQz&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;theme=light&amp;size=normal&amp;cb=htl08h3wtmsp']</value>
      <webElementGuid>e2e86983-ba59-4705-bae8-a8115f79046e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
