<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__a-ea9wlj8qeexe</name>
   <tag></tag>
   <elementGuidId>50bb7909-d46c-4afa-b37e-b4efd663b861</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;a-ea9wlj8qeexe&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name='a-ea9wlj8qeexe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;a-ea9wlj8qeexe&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>14bc131f-3c9c-4515-a7c1-9270337d8c25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>reCAPTCHA</value>
      <webElementGuid>db43d439-e47f-4eaf-80ab-cf70dedbff94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>304</value>
      <webElementGuid>6cdb6f6a-23b6-4ea8-9558-e2274af6ca64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>78</value>
      <webElementGuid>b12e001e-b00f-44cb-ba15-193e974dd2e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>presentation</value>
      <webElementGuid>babcc1dd-b7c0-4e80-9551-44052390f593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>a-ea9wlj8qeexe</value>
      <webElementGuid>86259380-eca2-44c4-803c-2a95aa679e63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c535d45d-cf77-4db7-af1d-03bfcfc8b4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>95b4c098-b6c1-42d8-a406-ec3549db3fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sandbox</name>
      <type>Main</type>
      <value>allow-forms allow-popups allow-same-origin allow-scripts allow-top-navigation allow-modals allow-popups-to-escape-sandbox allow-storage-access-by-user-activation</value>
      <webElementGuid>093500c7-922e-489b-8963-722db57660d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_&amp;co=aHR0cHM6Ly9zdGFnaW5nLnJhcmFtYXJrZXQuanA6NDQz&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;theme=light&amp;size=normal&amp;cb=t18446y63n57</value>
      <webElementGuid>6bc9a7fa-b142-4b2d-a8a6-eedb59868158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;g-recaptcha-response-value-281083db745449e0bac28311a218c1be&quot;)/div[1]/div[1]/iframe[1]</value>
      <webElementGuid>085d89a0-6e1b-46fb-a571-e3f76b48aa42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='a-ea9wlj8qeexe']</value>
      <webElementGuid>cbcba3ac-35c7-4c73-8acf-6792b6db3445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='g-recaptcha-response-value-281083db745449e0bac28311a218c1be']/div/div/iframe</value>
      <webElementGuid>fe88db7d-afca-4b6e-b722-4276a867e5ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>4a7c75a0-1a49-4d62-b13e-3e23056572c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'reCAPTCHA' and @name = 'a-ea9wlj8qeexe' and @src = 'https://www.google.com/recaptcha/api2/anchor?ar=1&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_&amp;co=aHR0cHM6Ly9zdGFnaW5nLnJhcmFtYXJrZXQuanA6NDQz&amp;hl=en&amp;v=-ZG7BC9TxCVEbzIO2m429usb&amp;theme=light&amp;size=normal&amp;cb=t18446y63n57']</value>
      <webElementGuid>bacb4c8f-aeee-41dc-bdb0-efdb8fac1fc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
