<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44</name>
   <tag></tag>
   <elementGuidId>cecb8f27-57ab-41e1-b3fb-b8c2233b06f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>td:nth-child(3) >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3ad47808-76f4-4c30-bd2d-d3fb259bcc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>586356cb-1475-4332-815d-aa17efefc85a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_</value>
      <webElementGuid>095158ef-bba3-43ed-969f-f19f51aa2c92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[1]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>b154af6e-7a04-4a75-ad69-c354442bad97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RaraMarket/Page_Register  Rara Market Japan/iframe_html1body1div4div4iframe1_c-8ktridki9qh2</value>
      <webElementGuid>6de593d5-bfae-4a93-ac96-c16bf875623b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr/td[3]/div/div/img</value>
      <webElementGuid>5c74acbc-713d-47fb-bd30-505175fd4bf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_')])[3]</value>
      <webElementGuid>6ff5c0b8-0179-4057-a192-41c95a5785bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/div/img</value>
      <webElementGuid>bc3f9be5-0bad-481a-9f4a-408bc6c875c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_']</value>
      <webElementGuid>6f6bba77-ed3a-45f1-88a7-d90be93754eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
