<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44_1</name>
   <tag></tag>
   <elementGuidId>947f51e9-b36c-4104-8886-3e3f8bd911aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(2) > td:nth-child(3)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>86e4aec2-51ce-46a7-9579-be497ca314d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>8c162137-01bd-4d11-b272-35bda943063e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_</value>
      <webElementGuid>7e07cab3-12de-4750-a747-da5f99776d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[2]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>7614b16a-94d5-4890-b092-a1c96a093a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RaraMarket/Page_Register  Rara Market Japan/iframe_html1body1div4div4iframe1_c-8ktridki9qh2</value>
      <webElementGuid>5894ff80-3e2a-4315-8a9c-78577b284c05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[2]/td[3]/div/div/img</value>
      <webElementGuid>8c1e2da5-3aa8-4dba-a9f1-672b378a7af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_')])[7]</value>
      <webElementGuid>8da1380b-fab3-46a1-b404-5bc9472c347c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/div/div/img</value>
      <webElementGuid>2fc0024b-e243-4d4e-a932-f4af8781a871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_']</value>
      <webElementGuid>c0d7c52a-0959-4f24-a743-afb7d14142a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
