<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44_1_2</name>
   <tag></tag>
   <elementGuidId>5510031c-6301-4d83-870b-3bf999b03f5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>35733c1a-1f01-4a82-94b3-95f6a7e3d90a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>b77f0396-7cda-4511-98e7-8b4f215b1f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_</value>
      <webElementGuid>45fde7e7-6598-40ef-87d7-155ecffac9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>7d05d117-2b51-4456-b54a-88417aa33b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RaraMarket/Page_Register  Rara Market Japan/iframe_html1body1div4div4iframe1_c-8ktridki9qh2</value>
      <webElementGuid>2ebdff8d-2a19-4eaf-8d9f-795aa0b39105</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td[2]/div/div/img</value>
      <webElementGuid>6469bdaf-ce26-4b05-a042-5086c7d21b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_')])[10]</value>
      <webElementGuid>666782ef-b9b6-4ca7-b36c-c52e39c7072a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div/div/img</value>
      <webElementGuid>38b6283d-ed3e-4990-8874-8dbd6c4ec1b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_']</value>
      <webElementGuid>960e81f3-baaa-42e2-b6a3-4e7a7ed5e9ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
