<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>6fb7cd1b-dddc-431c-bcf2-f0b79feaec47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(4) > td:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9f18001d-a243-4a01-b966-fc18f736d358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>44f750e2-38e4-4bff-b786-41b92d86f19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_</value>
      <webElementGuid>abcc8297-88cc-4fb8-a8e4-a1ff2aff0d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[4]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>cf589a5d-a0b8-4700-91ed-dd7f722f5377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RaraMarket/Page_Register  Rara Market Japan/iframe_html1body1div4div4iframe1_c-8ktridki9qh2</value>
      <webElementGuid>fe4d2b59-7b7a-4508-b571-c6ec264e448e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[4]/td[2]/div/div/img</value>
      <webElementGuid>dec72b04-c35c-4590-aee8-a29517d88209</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_')])[14]</value>
      <webElementGuid>1538c8ec-4baf-4596-bb1e-fca3471ca4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/div/div/img</value>
      <webElementGuid>d19190f2-31ff-4413-8d95-9fd2ae9f8361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_']</value>
      <webElementGuid>4fd40768-487b-4292-87cc-ea225dd6ea57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
