<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_traffic lights_rc-image-tile-44_1_2_3</name>
   <tag></tag>
   <elementGuidId>8d7bc8db-e629-406e-8b66-ce933a13a56d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(3) > td.rc-imageselect-tile > div.rc-image-tile-target > div.rc-image-tile-wrapper > img.rc-image-tile-44</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tr:nth-child(3) > td >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b1539278-a3a1-4b2f-89f0-d48b86354025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rc-image-tile-44</value>
      <webElementGuid>55d10bf0-e7a3-4029-9547-3306db192f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_</value>
      <webElementGuid>daa314d6-167a-41dd-8323-4bbff3bc3f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc-imageselect-target&quot;)/table[@class=&quot;rc-imageselect-table-44&quot;]/tbody[1]/tr[3]/td[@class=&quot;rc-imageselect-tile&quot;]/div[@class=&quot;rc-image-tile-target&quot;]/div[@class=&quot;rc-image-tile-wrapper&quot;]/img[@class=&quot;rc-image-tile-44&quot;]</value>
      <webElementGuid>8510639e-0573-433c-93e2-7176b144daad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/RaraMarket/Page_Register  Rara Market Japan/iframe_html1body1div4div4iframe1_c-8ktridki9qh2</value>
      <webElementGuid>dcfee400-fc10-4205-ab3d-299f31ab8bf5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rc-imageselect-target']/table/tbody/tr[3]/td/div/div/img</value>
      <webElementGuid>8706afe3-ad15-4b6c-9e7f-3571facf0c58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_')])[9]</value>
      <webElementGuid>d7765e55-8170-45db-85d2-2515045ded0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/div/div/img</value>
      <webElementGuid>c8f196b6-fe12-4d9d-98e9-d91d783932f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://www.google.com/recaptcha/api2/payload?p=06AFcWeA6cscirzNStn3V3Rb0U79RUzhb8BGdM3siGMQb5joazSJXU81f4DNZlSdgRb0wWMDZ-BGaQqJdUYF5LfuuC9qxX2L3zEptwx6V9wOY8cQzV6kMIUE_lzSFalULnCNJhurusP6eCjCGNumg9NBfgvKCdOZLn6prk4oTPr3GTuOLNhFGUanKSzvkcAq6RcfVJPmMOKWWXtIBunVp7FZuyBsums1jqXcVxRJ_h_5KgIml2yOvNzlk&amp;k=6LdAgJQpAAAAAHevNYbEmPXFWN6MByv36qzRBkw_']</value>
      <webElementGuid>165451a7-65e5-4840-aef8-c16fa3d247f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
