<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Search products_fa fa-user collapsed</name>
   <tag></tag>
   <elementGuidId>5e13db6a-c069-4b58-8f01-9d8023b16ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-user.collapsed</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/header/div/nav/div/div/div[3]/div/ul/div/ul/li[2]/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>91e5eae5-36f1-47d0-9bfe-8522d06020ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>31824f5e-5959-466f-837f-bb9f156f6380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>554ae1d7-488a-4863-96bb-fd3a8066fcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8d8b4f27-03ae-4f42-a9ea-f059375daa0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>sidebar-cart</value>
      <webElementGuid>716596ca-3aa9-4df2-aedb-556a4931220b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-user collapsed</value>
      <webElementGuid>a588f25e-91a6-4046-8b43-7c578406abb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>Login/Signup</value>
      <webElementGuid>8c998d0a-e2cd-44aa-8f8f-289ebdf225cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/header[@class=&quot;header&quot;]/div[@class=&quot;bottom-header&quot;]/nav[@class=&quot;navbar navbar-expand-lg&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row w-100 d-flex justify-content-between&quot;]/div[@class=&quot;bottom-header-area col-4  col-lg-4 pl-0 pl-xl-5 justify-content-end&quot;]/div[@class=&quot;heart-icon&quot;]/ul[@class=&quot;m-0 p-0 pl-0&quot;]/div[@class=&quot;d-inline-flex header-buttons&quot;]/ul[@class=&quot;mb-0  d-inline-flex sidebar-cart-items p-0&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;main-cart-icon hover-effect&quot;]/i[@class=&quot;fa fa-user collapsed&quot;]</value>
      <webElementGuid>47f22275-dae8-4594-b7b9-3451867e694d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/header/div/nav/div/div/div[3]/div/ul/div/ul/li[2]/a/i</value>
      <webElementGuid>6300b32d-2335-4499-b53e-98a11ca46422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a/i</value>
      <webElementGuid>302b5333-7ada-49c7-8000-6de8bd202113</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
